spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?createDatabaseIfNotExist=true
    username: root
    password: Bambademe99
    #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 8083

